// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBFcYjzp2raS7zbKGP1EsM2tYYKK45Hac',
    appId: '1:813302444240:web:dfb32011d788fe22c4eed5',
    messagingSenderId: '813302444240',
    projectId: 'jubileeinsurancelms',
    authDomain: 'jubileeinsurancelms.firebaseapp.com',
    storageBucket: 'jubileeinsurancelms.firebasestorage.app',
    measurementId: 'G-YQ0N4GE66J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbNUj-INbxtyJ1FGsioQXq_hC19BXcttk',
    appId: '1:813302444240:android:618ee972ed798f67c4eed5',
    messagingSenderId: '813302444240',
    projectId: 'jubileeinsurancelms',
    storageBucket: 'jubileeinsurancelms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3oPS4sOrUsLeg14TlvXgvU1A3JK9Oc68',
    appId: '1:813302444240:ios:ffa5182a2cf9e88cc4eed5',
    messagingSenderId: '813302444240',
    projectId: 'jubileeinsurancelms',
    storageBucket: 'jubileeinsurancelms.firebasestorage.app',
    iosBundleId: 'com.legal.app',
  );
}
